version: '3'

services:
  esclave:
    build: ./esclave
    environment:
      - HASH
    depends_on:
      - maitre
  maitre:
    build: ./maitre
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
